server:
  port: 8081
spring:
  application:
    name: "AUTENTICACION"
  devtools:
    add-properties: false
  profiles:
    include: null
  flyway:
    url: "jdbc:mysql://localhost:3306/auth_db"
    user: "jpriva"
    password: "pass12345"
    locations: "classpath:db/migration"
    enabled: true
adapters:
  r2dbc:
    host: "localhost"
    port: 3306
    database: "auth_db"
    username: "jpriva"
    password: "pass12345"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
