##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: AUTENTICACION
  devtools:
    add-properties: false
  profiles:
    include:
  flyway:
    url: jdbc:mysql://localhost:3306/auth_db
    user: jpriva
    password: pass12345
    locations: classpath:db/migration
    enabled: true

adapters:
  r2dbc:
    host: localhost
    port: 3306
    database: auth_db
    username: jpriva
    password: pass12345
