server:
  port: 8081

spring:
  application:
    name: "AUTENTICACION"
  devtools:
    add-properties: false
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
  flyway:
    url: jdbc:mysql://${SPRING_R2DBC_HOST:localhost}:${SPRING_R2DBC_PORT:3306}/${SPRING_R2DBC_DB:auth_db}
    user: ${SPRING_DB_USERNAME}
    password: ${SPRING_DB_PASSWORD}
    locations: "classpath:db/migration"
    enabled: true
  output:
    ansi:
      enabled: ALWAYS

adapters:
  r2dbc:
    host: ${SPRING_R2DBC_HOST:localhost}
    port: ${SPRING_R2DBC_PORT:3306}
    database: ${SPRING_R2DBC_DB:auth_db}
    username: ${SPRING_DB_USERNAME}
    password: ${SPRING_DB_PASSWORD}

management:
  endpoints:
    web:
      base-path: "/auth/actuator"
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8081}"

springdoc:
  api-docs:
    info:
      title: "Crediya Auth API Microservice"
      version: "1.0.0"
      description: "This is the API for Crediya Auth Microservice"
  swagger-ui:
    path: /auth/swagger-ui.html
    public-urls:
      - /api/v1/auth/login
  paths-to-exclude:
    - /api/v1/usuarios/{idNumber}
    - /api/v1/busquedas/emails
    - /api/v1/busquedas/filtro

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:3600}

app:
  default-admin:
    email: ${APP_DEFAULT-ADMIN_EMAIL}
    password: ${APP_DEFAULT-ADMIN_PASSWORD}
  default-super-user:
    email: ${APP_DEFAULT-SUPER_EMAIL}
    password: ${APP_DEFAULT-SUPER_PASSWORD}
