spring:
  flyway:
    url: jdbc:mysql://${SPRING_R2DBC_HOST:localhost}:${SPRING_R2DBC_PORT:3306}/${SPRING_R2DBC_DB:auth_db}
    user: ${SPRING_DB_USERNAME:jpriva}
    password: ${SPRING_DB_PASSWORD:pass12345}

adapters:
  r2dbc:
    host: ${SPRING_R2DBC_HOST:localhost}
    port: ${SPRING_R2DBC_PORT:3306}
    database: ${SPRING_R2DBC_DB:auth_db}
    username: ${SPRING_DB_USERNAME:jpriva}
    password: ${SPRING_DB_PASSWORD:pass12345}

security:
  jwt:
    secret: ${JWT_SECRET:iBdGbA8Dxowf12Zs7IYH91+KwKOg5yb39RGQv6pOWes=}

app:
  default-admin:
    email: ${APP_DEFAULT-ADMIN_EMAIL:admin@crediya.com}
    password: ${APP_DEFAULT-ADMIN_PASSWORD:admin1234}
  default-super-user:
    email: ${APP_DEFAULT-SUPER_EMAIL:super@crediya.com}
    password: ${APP_DEFAULT-SUPER_PASSWORD:super1234}
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8083}"
