server:
  port: 8081

spring:
  application:
    name: "AUTENTICACION"
  devtools:
    add-properties: false
  profiles:
    include: null
  flyway:
    url: jdbc:mysql://${SPRING_R2DBC_HOST:localhost}:${SPRING_R2DBC_PORT:3306}/${SPRING_R2DBC_DB:auth_db}
    user: ${SPRING_DB_USERNAME:jpriva}
    password: ${SPRING_DB_PASSWORD:pass12345}
    locations: "classpath:db/migration"
    enabled: true
  output:
    ansi:
      enabled: ALWAYS

adapters:
  r2dbc:
    host: ${SPRING_R2DBC_HOST:localhost}
    port: ${SPRING_R2DBC_PORT:3306}
    database: ${SPRING_R2DBC_DB:auth_db}
    username: ${SPRING_DB_USERNAME:jpriva}
    password: ${SPRING_DB_PASSWORD:pass12345}

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  server:
    port: 9090

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"

springdoc:
  api-docs:
    info:
      title: "Crediya Auth API Microservice"
      version: "1.0.0"
      description: "This is the API for Crediya Auth Microservice"
  swagger-ui:
    path: /swagger-ui.html
    public-urls:
      - /api/v1/auth/login
  paths-to-exclude:
    - /api/v1/usuarios/{idNumber}
    - /api/v1/busquedas/emails
    - /api/v1/busquedas/filtro


logging:
  level:
    org.springframework.transaction.reactive: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:6wmLjTUj5h4CXtp23BPjlr2IouInKGEBhqVi+LkR1KlIisuE4dKm4vbwWhUKwPsg53CjqX5Uu2L8TshpLXPdWA==}
    expiration: 3600

app:
  default-admin:
    email: ${APP_DEFAULT-ADMIN_EMAIL:admin@crediya.com}
    password: ${APP_DEFAULT-ADMIN_PASSWORD:admin1234}
